# Generated by Django 5.1.3 on 2025-06-16 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skill",
            name="level",
            field=models.CharField(
                choices=[
                    ("BASIC", "BASIC"),
                    ("INTERMEDIATE", "INTERMEDIATE"),
                    ("ADVANCED", "ADVANCED"),
                ],
                verbose_name="skill level",
            ),
        ),
    ]
